---
- name: backup http.conf
  shell: cp /etc/httpd/conf/httpd.conf /etc/httpd/conf/httpd_default.conf
  become: true
  become_user: root  
  tags: [apache]


- name: Set Up http.conf
  template:
    src: "files/httpd.conf"
    dest: "/etc/httpd/conf"
  tags: [apache]

- name: Restart Apache
  service:
    name: httpd
    state: restarted
  tags: [apache]
  
