---
- name: Include variables
  include_vars: 
    file: settings.yml

- name: Get the MySQL 5.7 repository
  yum:
    name: https://dev.mysql.com/get/mysql57-community-release-el7-9.noarch.rpm
    state: present    
  become: true
  become_user: root

- name: Install MySQL 5.7
  yum:
    name: 
      - mysql-community-server
      - mysql-community-client
      - MySQL-python
    state: installed

- name: Ensure mysql is started
  service:
    name: mysqld
    state: started
    enabled: yes

- name: Find MySQL root password
  shell: "grep 'temporary.*root@localhost' /var/log/mysqld.log | sed 's/.*root@localhost: //'"
  register: mysql_root_pass

- name: Change password
  shell: >
    mysql -e "SET PASSWORD = PASSWORD('{{ MYSQL_NEW_ROOT_PASSWORD }}');"
    --connect-expired-password -uroot -p"{{ mysql_root_pass.stdout }}"
  args:
    creates: /root/.my.cnf

- name: Copy my.cnf file with root password credentials
  template: 
    src: "files/.my.cnf"
    dest: "/root/.my.cnf"
    owner: root
    mode: 0600

- name: restart mysqld
  service: 
    name: mysqld 
    state: restarted